spring:
  config:
    import:
      - classpath:config/ip.yml
      - classpath:config/database.yml
  profiles:
    group:
      "prod":
        #        - prod-db TODO
        - prod-ip
      "local":
        #        - prod-db TODO
        - local-ip

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-dq67l.pub-cdb.ntruss.com:3306/mococo
    username: hyeon
    password: Signal3700

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto:  update


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 5000
  error:
    whitelabel:
      enabled: false
